server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: xxx
    password: xxx
    url: jdbc:mysql://xxx.xxx.xxx.xxx:3306/xxx?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC